// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhARkKYIij5edDM4HfEHkwqgQ4FhtQfAk',
    appId: '1:157895668454:web:0c24e49abeb3a74c824127',
    messagingSenderId: '157895668454',
    projectId: 'chat-app-d4588',
    authDomain: 'chat-app-d4588.firebaseapp.com',
    storageBucket: 'chat-app-d4588.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwpteExTDJ4DiblhcGEWr_ojTIr_ZElw',
    appId: '1:157895668454:android:d1b5c143f37bc640824127',
    messagingSenderId: '157895668454',
    projectId: 'chat-app-d4588',
    storageBucket: 'chat-app-d4588.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjjeJImyUZEYM9AZ2J_LrAW8sXAje9QqY',
    appId: '1:157895668454:ios:75f09c2ef8a7c2a8824127',
    messagingSenderId: '157895668454',
    projectId: 'chat-app-d4588',
    storageBucket: 'chat-app-d4588.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjjeJImyUZEYM9AZ2J_LrAW8sXAje9QqY',
    appId: '1:157895668454:ios:6ff6127cedbf4789824127',
    messagingSenderId: '157895668454',
    projectId: 'chat-app-d4588',
    storageBucket: 'chat-app-d4588.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
